package com.am.modules.repertory.entity;

import com.am.common.baseEntity.DataEntity;

public class Repertory extends DataEntity<Repertory> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.surplus
     *
     * @mbggenerated
     */
    private Float surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.units
     *
     * @mbggenerated
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repertory.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repertory
     *
     * @mbggenerated
     */
    public Repertory(Integer id, String name, Float surplus, String units, Integer del) {
        this.id = id;
        this.name = name;
        this.surplus = surplus;
        this.units = units;
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.ID
     *
     * @return the value of repertory.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.name
     *
     * @return the value of repertory.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.surplus
     *
     * @return the value of repertory.surplus
     *
     * @mbggenerated
     */
    public Float getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.units
     *
     * @return the value of repertory.units
     *
     * @mbggenerated
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repertory.del
     *
     * @return the value of repertory.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }
}