package com.am.modules.goods.entity;

import com.am.common.baseEntity.DataEntity;

public class Goods extends DataEntity<Goods>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    public Goods(Integer id, String name, String money, Integer del) {
        this.id = id;
        this.name = name;
        this.money = money;
        this.del = del;
    }

    public Goods(){}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.ID
     *
     * @return the value of goods.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.money
     *
     * @return the value of goods.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.del
     *
     * @return the value of goods.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setMoney(String money) {
        this.money = money;
    }
}