package com.am.modules.user.entity;

import com.am.common.baseEntity.DataEntity;

public class User extends DataEntity<User>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.oppenid
     *
     * @mbggenerated
     */
    private String oppenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phonenumber
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vip
     *
     * @mbggenerated
     */
    private Integer vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User(Integer id, String name, String oppenid, String phonenumber, Integer vip, Integer del) {
        this.id = id;
        this.name = name;
        this.oppenid = oppenid;
        this.phonenumber = phonenumber;
        this.vip = vip;
        this.del = del;
    }

    public User(){};
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.oppenid
     *
     * @return the value of user.oppenid
     *
     * @mbggenerated
     */
    public String getOppenid() {
        return oppenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phonenumber
     *
     * @return the value of user.phonenumber
     *
     * @mbggenerated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vip
     *
     * @return the value of user.vip
     *
     * @mbggenerated
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del
     *
     * @return the value of user.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }


    public void setName(String name) {
        this.name = name;
    }

    public void setOppenid(String oppenid) {
        this.oppenid = oppenid;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public void setVip(Integer vip) {
        this.vip = vip;
    }
}