package com.am.modules.adminUser.dao;

import com.am.common.dao.MybatisDao;
import com.am.modules.adminUser.entity.AdminUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;
@MybatisDao
public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from admin_user",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     * @mbggenerated
     */
    @Insert({
        "insert into admin_user (ID, admin_name, ",
        "password, codeid, ",
        "permission, del)",
        "values (#{id,jdbcType=INTEGER}, #{adminName,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{codeid,jdbcType=VARCHAR}, ",
        "#{permission,jdbcType=INTEGER}, #{del,jdbcType=INTEGER})"
    })
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, admin_name, password, codeid, permission, del",
        "from admin_user",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    AdminUser selectByPrimaryKey(Integer id);

    AdminUser findByCodeId(String codeid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated
     */
    @Update({
        "update admin_user",
        "set admin_name = #{adminName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "codeid = #{codeid,jdbcType=VARCHAR},",
          "permission = #{permission,jdbcType=INTEGER},",
          "del = #{del,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AdminUser record);

    int deleteByID(int id);
    List<AdminUser> findAll();
}